In [5]:
import pandas as pd

In [6]:
book_df=pd.read_csv("BooksDatasetClean.csv")
book_df.head(10)

,Title,Authors,Description,Category,Publisher,Price Starting With ($),Publish Date (Month),Publish Date (Year)
0,Goat Brothers,"By Colton, Larry",NaN,"History , General",Doubleday,8.79,January,1993
1,The Missing Person,"By Grumbach, Doris",NaN,"Fiction , General",Putnam Pub Group,4.99,March,1981
2,Don't Eat Your Heart Out Cookbook,"By Piscatella, Joseph C.",NaN,"Cooking , Reference",Workman Pub Co,4.99,September,1983
3,When Your Corporate Umbrella Begins to Leak: A...,"By Davis, Paul D.",NaN,NaN,Natl Pr Books,4.99,April,1991
4,Amy Spangler's Breastfeeding : A Parent's Guide,"By Spangler, Amy",NaN,NaN,Amy Spangler,5.32,February,1997
5,The Foundation of Leadership: Enduring Princip...,"By Short, Bo",NaN,NaN,Excalibur Press,6.06,January,1997
6,Chicken Soup for the Soul: 101 Stories to Open...,"By Canfield, Jack (COM) and Hansen, Mark Victo...",NaN,"Self-help , Personal Growth , Self-Esteem",Health Communications Inc,4.99,May,1993
7,Journey Through Heartsongs,"By Stepanek, Mattie J. T.",Collects poems written by the eleven-year-old ...,"Poetry , General",VSP Books,19.96,September,2001
8,In Search of Melancholy Baby,"By Aksyonov, Vassily, Heim, Michael Henry, and...",The Russian author offers an affectionate chro...,"Biography & Autobiography , General",Random House,4.99,June,1987
9,Christmas Cookies,"By Eakin, Katherine M. and Deaman, Joane (EDT)",NaN,"Cooking , General",Oxmoor House,12.98,June,1986

In [7]:
#delete rows with NaN values

In [8]:
book_df = book_df.dropna()
book_df.head(10)

,Title,Authors,Description,Category,Publisher,Price Starting With ($),Publish Date (Month),Publish Date (Year)
7,Journey Through Heartsongs,"By Stepanek, Mattie J. T.",Collects poems written by the eleven-year-old ...,"Poetry , General",VSP Books,19.96,September,2001
8,In Search of Melancholy Baby,"By Aksyonov, Vassily, Heim, Michael Henry, and...",The Russian author offers an affectionate chro...,"Biography & Autobiography , General",Random House,4.99,June,1987
10,The Dieter's Guide to Weight Loss During Sex,"By Smith, Richard","A humor classic, this tongue-in-cheek diet pla...","Health & Fitness , Diet & Nutrition , Diets",Workman Publishing Company,4.99,January,1978
11,Germs : Biological Weapons and America's Secre...,"By Miller, Judith, Engelberg, Stephen, and Bro...","Deadly germs sprayed in shopping malls, bomb-l...","Technology & Engineering , Military Science",Simon & Schuster,4.99,October,2001
13,The Good Book: Reading the Bible with Mind and...,"By Gomes, Peter J.","""The Bible and the social and moral consequenc...","Religion , Biblical Biography , General",Harper Perennial,5.29,May,1998
14,All over but the Shoutin',"By Bragg, Rick",A New York Times Notable Book of the YearThis ...,"Biography & Autobiography , Personal Memoirs",Vintage,4.89,September,1998
19,Hill Rat: Blowing the Lid Off Congress,"By Jackley, John L.",As a top aide to powerful Texas Congressman Ro...,"Political Science , General","Regnery Publishing, Inc.",4.99,April,1992
21,Personality of the Cat,"By Aymar, Brandt (EDT)",A delightful collection of reflections on the ...,"Pets , Cats , General",Bonanza Books,5.41,January,1978
26,Betrayal : How the Clinton Administration Unde...,"By Gertz, Bill","Gertz, writer for the Moonie-influenced Washi...","Political Science , General",Regnery Pub,4.99,May,1999
27,Shadow Song,"By Kay, Terry","It was a wonderful summer, a great memory, the...","Fiction , General",Atria Books,4.99,October,1994

In [50]:
#delete not relavat colums

In [52]:
book_df = book_df.drop(columns=['Price Starting With ($)', 'Publish Date (Month)', 'Publish Date (Year)'])
book_df.head(10)

KeyError: "['Price Starting With ($)', 'Publish Date (Month)', 'Publish Date (Year)'] not found in axis"

In [ ]:
#make the database smaller

In [ ]:
print(len(book_df))

In [ ]:
book_df=book_df.head(200)
print(len(book_df))

In [ ]:
#embending with BERT

In [ ]:
from sentence_transformers import SentenceTransformer
model = SentenceTransformer("all-MiniLM-L6-v2")

In [ ]:
#encode in embendding work only with string/ list, so we need to convert the data frame to list

In [60]:
texts = (
    book_df["Title"].fillna("") + ". " +
    book_df["Authors"].fillna("") + ". "+
    book_df["Description"].fillna("") + ". " +
    book_df["Category"].fillna("") + ". " +
    book_df["Publisher"].fillna("")
)

book_embeddings = model.encode(
    texts.tolist(),
    normalize_embeddings=True
)

In [61]:
#embendding to the client request

In [62]:
def get_user_embedding(user_query, model):
    return model.encode(user_query, normalize_embeddings=True)

In [63]:
#check similarity

In [64]:
from sklearn.metrics.pairwise import cosine_similarity

def get_similarity_scores(user_embedding, book_embeddings):
    return cosine_similarity([user_embedding], book_embeddings)[0]

In [65]:
#bring top 5 recommends

In [66]:
import numpy as np

def get_top_books(book_df, semantic_scores, top_n=5):
    top_idx = np.argsort(semantic_scores)[::-1][:top_n]
    return book_df.iloc[top_idx]

In [67]:
#final: call to all the function

In [78]:
user_query = input("what do you want?")
user_embedding = get_user_embedding(user_query, model)
semantic_scores = get_similarity_scores(user_embedding, book_embeddings)
top_books = get_top_books(book_df, semantic_scores)

#print(top_books[["Title", "Authors", "Description"]])
top_books

what do you want? history

,Title,Authors,Description,Category,Publisher
358,Grandparenthood,"By Westheimer, Ruth K. and Kaplan, Steven",First published in 2000. Routledge is an impri...,"Social Science , Gerontology",Routledge
405,The World of the Ancient Maya,"By Henderson, John S.","""General overview of the ancient Maya begins w...","Social Science , Archaeology",Cornell Univ Pr
376,Americas: The Changing Face of Latin America a...,"By Winn, Peter","Stunning in its sweep, Americas is the most au...","Social Science , Anthropology , Cultural & So...",University of California Press
51,George Meany And His Times: A Biography,"By Robinson, Archie",Draws on interviews and unpublished documents ...,"Biography & Autobiography , General",Simon & Schuster
73,"New Lands, New Men","By Goetzmann, William H.",Examines the adventures of the explorers durin...,"Biography & Autobiography , Adventurers & Exp...",Viking Adult

In [ ]:
def book_by_category(category, score):
    adjust_scores=score
    for i, row in book_df.iterrows():
        if row['Category'] == category:
        adjusted_scores[i] += 0.3
    return adjust_scores